Switch back to Rails dependency (#409)
In [Remove dependence on mimemagic gem](https://github.com/DEFRA/sroc-tcm-admin/pull/405) we needed to switch from referencing the `rails` gem to referencing directly the underlying gems whilst avoiding any with a link to [Marcel](https://github.com/rails/marcel) and its dependence on [MimeMagic](https://github.com/mimemagicrb/mimemagic).

The Rails team have [since resolved the issue](https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/) so we can happily go back to just referencing the `rails` as would normally be expected 😁

** Note - update pg gem

Resolves following error seen when running migrations after the `bundle update`

```
rake aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? can't activate pg (~> 1.1), already activated pg-0.21.0. Make sure all dependencies are added to Gemfile.
```